### ISSUE TITLE
Able to add God of Thunder to any weapon

### ISSUE THREAD

**Issue by WachumaFox** [Safrodev/fabricenchantments#11]
![image](https://user-images.githubusercontent.com/53717728/127059031-d52d0c32-34c4-4c8b-90e7-334a5ae8e6b5.png)
I was able to add God of Thunder onto a hoe in survival, when it should only be able to be put on an axe? I am also able to put it on a sword, is this intentional, despite it saying "Axes only" on the curseforge page? 

This is 0.3.2 on latest fabric 1.17.1

**Comment by Safrodev** [comment]
This is a bug because with enchantments you can only specifiy what tool type they are for. In this case the tool type is MAIN_HAND which works for any sword, axe, pickaxe, shovel, or hoe. I will try to look for a work-around and see how other mods do it.
