### ISSUE TITLE
My game crashes with the mod in 1.17.1

### ISSUE THREAD

**Issue by RetroGameDays36** [Safrodev/fabricenchantments#12]
[crashhh.txt](https://github.com/Safrodev/fabricenchantments/files/6895061/crashhh.txt)

I'm using the 0.4.0 version and whenever i try to start the game up it crashes, before it even opens the game.

**Comment by Safrodev** [comment]
Okay so the error does not seem to be specifically with code. It seems that the name of the mixin/method in Fabric Enchantments is the same as another mod. I will have to change it but this crash only happens when you use “Mo Enchantments” with this mod.
