### ISSUE TITLE
Fabric Enchantments 0.4.1 update made the mixins clash with the ones from sihywtcamd and crash the game on startup

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [Safrodev/fabricenchantments#14]
**MC** 1.17.1
**Fabric API** 0.37.1
**Fabric Enchantments** 0.4.1
**So I heard you were talking shit about Minecraft difficulty** 1.3.1
*[Mod page](https://www.curseforge.com/minecraft/mc-mods/sihywtcamd)*

When trying to start the game with both mods present, it will crash before fully initializing. I know there's a 1.4.1 version of sihywtcamd, but I'm intentionally not using that one as it causes issues at the moment with the negative Y. And I assume both would still clash with Fabric Ecnhantments. FE 0.4.0 and 0.3.2 work just fine.

<details>
  <summary>Mixin clash in question</summary>
  
Mixin apply failed sihywtcamd.mixins.json:EndermanMixin -> net.minecraft.class_1560: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1560::addBlindnessE with priority 1000 cannot inject into net/minecraft/class_1560::method_7026(Lnet/minecraft/class_1657;)Z merged by safro.fabric.enchantments.mixin.enchantment.PumpkinHeadMixin with priority 1000 [PREINJECT Applicator Phase -> sihywtcamd.mixins.json:EndermanMixin -> Prepare Injections ->  -> handler$caf000$addBlindnessE(Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1560::addBlindnessE with priority 1000 cannot inject into net/minecraft/class_1560::method_7026(Lnet/minecraft/class_1657;)Z merged by safro.fabric.enchantments.mixin.enchantment.PumpkinHeadMixin with priority 1000 [PREINJECT Applicator Phase -> sihywtcamd.mixins.json:EndermanMixin -> Prepare Injections ->  -> handler$caf000$addBlindnessE(Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]

</details>

Full log: [latest.log](https://github.com/Safrodev/fabricenchantments/files/6901617/latest.log)

**Comment by Safrodev** [comment]
I should've known this would happen because I overwrote the isPlayerStaring method for the Enderman. I will need to find a better way to do the pumpkin head enchantment without overwriting the method but for now, you will need to choose one of the mods to remove.
