### ISSUE TITLE
Tank enchantment works on leggings 

### ISSUE THREAD

**Issue by BloodStainsTR** [Safrodev/fabricenchantments#17]
Title explains it all
![image](https://user-images.githubusercontent.com/56932912/128714739-2e5a80c0-f41d-4214-bc81-6a8743582dce.png)

Tested on v4.0.1 for 1.16.5

**Comment by Safrodev** [comment]
This is a known issue that happens because Minecraft locks enchanting items through the anvil. I have fixed it in a past version but it was causing crashes with other mods. I'm working on getting a stable fix soon!
