### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Timolino456** [Safrodev/fabricenchantments#23]
I have two suggestions for the mod.

The first one is better names for some of the enchantments (if they aren't already specifically intended to be named like they are)

Ice Aspect could be called Frostbite, Poison Aspect could be called Venom or Venomous, mostly to not just copy the "aspect" part of the name.

Experience could be called Wisdom or something similar.

Rise could be called Ascension or Levitation like the effect is called, since it pretty much does that.

Sugar Rush could be called something like Blood Rush instead, I don't really see any connection with sugar other than being faster and sugar being used for speed potions, and it would sound cooler and make a bit more sense, since armor is for fighting. :D

The second suggestion is some feature ideas regarding ranged weapons:

- Make Power, Flame, Punch and Infinity work with crossbows with the same rules they have on bows. Incompatibility with the Infinity Fix mod might be possible here since it also adds infinity support for crossbows, I guess it would just be best to make your mod automatically disable the infinity part when having both installed since Infinity Fix also makes Infinity and Mending work together? Not sure though since I'm not a modder myself...

- Make Multishot and Piercing work with normal bows. Maybe Quick Charge too, although the name wouldn't really fit, a new enchantment that does the same thing, called Quick Draw might be better, since I don't think you can make enchanments have different names when used on different items. Also fewer levels (one or two) might be more appropriate since drawing a bow is already faster than charging a crossbow.

**Comment by Safrodev** [comment]
I really like these renaming ideas but I tried to keep the enchantment names simple so people could understand their uses without reading the mod page. I'll consider the vanilla enchantment changes but I believe there are mods that already do this. (Sorry for the extremely late reply)
