### ISSUE TITLE
Incompatible with Mo Enchantments

### ISSUE THREAD

**Issue by mastery3** [Safrodev/fabricenchantments#26]
Fabric Enchantments and Mo' Enchantments together breaks the Alpha Fire enchantment from Mo' Enchantments.

(Tested with Fabric Enchantments 0.5.0 release and Mo' Enchantments 1.17.1 & 1.18.1 since their version system is confusing af)

**Comment by Safrodev** [comment]
I will have to look into this but could you possibly send any logs you received from this crash? Thanks and sorry for the late reply.

**Comment by mastery3** [comment]
It does not crash; it overrides Alpha Fire.
No output from console.

**Comment by Safrodev** [comment]
Hmm interesting, I'll see if I can recreate it and hopefully get it fixed

**Comment by Safrodev** [comment]
I seemed to have found the problem. Both of us mixin to a similar place and use a "RETURN" mixin. Both alpha fire and this mod's auto smelt enchantment do the same thing so there's nothing much I can do about it. It's up to you whether you want to use auto smelt instead or remove this mod. Sorry for the inconvience.

**Comment by mastery3** [comment]
Unfortunately, I can't use auto smelt because it doesn't offer customizability on which blocks would be smelted; I have the Better Nether mod and mining obsidian would give me obsidian glass.

I decided to manually edit the mod and remove the mixin.
