### ISSUE TITLE
Tank Stopped Giving Hearts?

### ISSUE THREAD

**Issue by ImPagani** [Safrodev/fabricenchantments#34]
Am playing Another Quality Modpack 2 v1.4.1. I take off my armor to let my friend hit me and test damage. Once I put back on my chestplate, I don't have my extra hearts anymore and am back to base 10. Putting on a different piece of armor with Tank did nothing as well. Any help on this would be awesome.

**Comment by Safrodev** [comment]
Tank was reworked in v0.5.0 and it no longer grants extra heart. Please refer to the project page for it’s new abilities.

**Comment by ImPagani** [comment]
Oh, okay. Sorry for the inconvenience, thank you for the response!
