### ISSUE TITLE
Not working properly on servers

### ISSUE THREAD

**Issue by NerdyTrout** [Safrodev/fabricenchantments#35]
Me and my friend are playing on fabric server and I installed this mod to my server. I also dropped my server's mod folder to my friend. For me, everything works just fine, but my friend is experiencing troubles joining. Again, we are having all the exact mod, and there were no problems until now. Here's the error message when he join:
![unknown](https://user-images.githubusercontent.com/98548723/151415373-44b166e8-6eac-4b32-b421-3efdfb617f22.png)
.

The problem went away once i deleted the mod from the server.

**Comment by Safrodev** [comment]
This error happens if the client is missing mods from the server. I believe your friend has a different Fabric Enchantments version than the server?
