### ISSUE TITLE
Make this mod compatible with Haema

### ISSUE THREAD

**Issue by NyanMaths** [Safrodev/fabricenchantments#36]
In short , [Haema](https://www.curseforge.com/minecraft/mc-mods/haema) is a mod that allows you to become a vampire, and logically, you do not have hunger, but blood bar. I just would want you to make consume enchantment work with the blood bar. Thank you by advance !

**Comment by Safrodev** [comment]
Interesting, I'll see if I can do it

**Comment by NyanMaths** [comment]
Thanks a lot ! May be you should let it configurable because it is quite OP and not everybody would want to make this possible, but it would get a bit complicated for a simple compatibility.

**Comment by Safrodev** [comment]
Wasn't able to get it working properly so unfortunately I'm going to have to scrap this.

**Comment by NyanMaths** [comment]
Oh too bad, thank you anyway !
