### ISSUE TITLE
[Suggestion Box] More Enchantments

### ISSUE THREAD

**Issue by jett42069** [Safrodev/fabricenchantments#37]
Just dumping some suggestions here, let me know what you think :)

**Vampirism** - sword, axe, and trident - you are healed for a percentage of the damage you deal to your enemy. Vampirism I = 10%, Vampirism II = 20%, etc. up to Vampirism V. Not compatible with Consume. Treasure only book found in dungeons and strongholds.

**Evoker's Wrath** - sword enchantment - right click summons a line of 16 evoker fangs exactly like his attack, with a 10 second cooldown. Book is a rare drop from evokers. Bonus points if you can get in the silly evoker arm wave when you do the attack.

**Hyperbeam** - trident enchantment - trident can no longer be thrown, holding right click summons a guardian beam from the end, active for 15 seconds at a time max with a 10 second cooldown. Book is a rare drop from elder guardians. Hyperbeam II allows you to hold it for 30 seconds with a 15 second cooldown. If combined with Loyalty the items go directly to your inventory, since it's a ranged attack.

**Comment by Safrodev** [comment]
Pretty nice suggestions! I will consider adding some of these, though I’ll have to make sure it the right-click ones don’t conflict with other mods.
