### ISSUE TITLE
suggestion to make it work server-side

### ISSUE THREAD

**Issue by Leka1B** [Safrodev/fabricenchantments#38]
I mange a server for my friend group, and many of them don't have or know how to install fabric. I usually installed everyting on the server to make it work for everyone, but this mod disagrees with this tactic.

When installed server-side:
-Enchantment table shows empty popups instead of enchantment name (the vanilla ones are still visible)
-After clicking the empty enchantment you lose xp, but nothing new appears on the item

I installed the mod locally and the table now has the enchants like it should. The items still don't have the effects of the seemingly empty table entries i mentioned before.

After removing it from my game (with the mod still installed on the server) I once againg do not see the enchantments i made on my items, but they still work. Weird.

Would be very glad if you fixed that, the mod is really cool!

**Comment by Safrodev** [comment]
The mod used to work server side actually, but I’m still wondering why it stopped after a certain update. I’ll look into it more but it shouldn’t be requiring anything on the client.
