### ISSUE TITLE
Translations and enchantments suggestion

### ISSUE THREAD

**Issue by Taldariner** [Safrodev/fabricenchantments#5]
I can provide Russian and Ukrainian translations if needed.

Suggested enchantments:

Chestplate:
- Spiky armor: deal damage to anyone that dealt damage to you
- Weighting: makes you move slower, but reduce the effect of knockbacks

Helmet:
- Oxygen absorber: reduce the speed of oxygen usage while underwater

Bow:
- Charge: arrows fly further and in a straighter trajectory

Sword:
- Dismemberment: a low chance to one-shot regular mob(which have up to 10 maximum HP or something like that)
- Combo(level I-III): gives small chances to attack two or three times by one click
- Behinding: gives small chance to teleport behind enemy after attacking it

Pickaxe:
- Detector: visual effects if there are any ores nearby(constant or after any block breaking)

**Comment by RDKRACZ** [comment]
> Oxygen absorber: reduce the speed of oxygen usage while underwater

? Respiration

> Spiky armor: deal damage to anyone that dealt damage to you

Thorns?

> Charge: arrows fly further and in a straighter trajectory

That's kinda base mechanic of a bow but sure, making the charge stronger by enchant is good.

**Comment by Taldariner** [comment]
> > Oxygen absorber: reduce the speed of oxygen usage while underwater
> 
> ? Respiration
> 
> > Spiky armor: deal damage to anyone that dealt damage to you
> 
> Thorns?
> 
> > Charge: arrows fly further and in a straighter trajectory
> 
> That's kinda base mechanic of a bow but sure, making the charge stronger by enchant is good.

Well, I didn't found enchantmens like Thorns and Respiration on mod Curseforge page or your post on Github, so decided to write it. Can be my miss, but anyway, better write twice than never.

**Comment by RDKRACZ** [comment]
Uhh, but these two are vanilla enchantments.

**Comment by Taldariner** [comment]
> Uhh, but these two are vanilla enchantments.

Then sorry, my mistake. Never used vanilla enchantments much.

**Comment by Safrodev** [comment]
Thank you for the suggestions. I’ll have a look through these and maybe add some! I’d also love it you would like to do Russian + Ukrainian translations. If you make the translations you can open a new issue with the lang file or create a pull request.
