### ISSUE TITLE
Tank Enchantment

### ISSUE THREAD

**Issue by Adraxion** [Safrodev/fabricenchantments#53]
Enchanting chest armor with tank removes armor value from the item

**Comment by Austin001316** [comment]
Can confirm this is happening on 1.19.2
![image](https://user-images.githubusercontent.com/91763031/194804205-0ff93aa8-c5ac-43ac-a3e8-f4748fea2627.png)

**Comment by Safrodev** [comment]
Does this make the chestplate stop displaying the armor value or does it not give the armor points either.

**Comment by Austin001316** [comment]
It doesn't display or give your any armor value with the enchant applied

**Comment by Adraxion** [comment]
Can confirm that the armor value appears to be replaced by the health buff in 1.19.2.

**Comment by notIkibo** [comment]
Yes, I was just about to state that problem. With that bug, Tank is practically a debuff. At least you can disable different enchantments (for now).

**Comment by Safrodev** [comment]
Should be fixed in v0.9.0 sorry bout that
