### ISSUE TITLE
[1.18.2] Mod is incompatible with an enchantment from Incantationem Mod

### ISSUE THREAD

**Issue by ConqAra** [Safrodev/fabricenchantments#54]
Tested on 1.18.2
When fabric enchantments is installed with incantationem, the forging touch mod from incantationem does not work.
Posting this here to let you know.
Link to Issue: [https://github.com/Luligabi1/Incantationem/issues/22](https://github.com/Luligabi1/Incantationem/issues/22)

**Comment by Safrodev** [comment]
I see the problem, both mods mixin to the same method but FE returns a value without giving Incantationem a chance to run its own code. This should be a simple fix but it will go out for 1.19.2.

**Comment by ConqAra** [comment]
Aww. Welp hopefully incantationem has its own way to fix for 1.18.2

**Comment by Safrodev** [comment]
Hopefully, I've fixed it for 1.19.2 if you'd like to switch to that version.
