### ISSUE TITLE
Traditional Chinese translation

### ISSUE THREAD

**Issue by oddcrafti** [Safrodev/fabricenchantments#55]
I have a reply on the CurseForge page, now I submit it

Language : Traditional Chinese 繁體中文(台灣)
---
Consume I-III: Upon killing an entity there is a 10-30% chance(depends on level) that your hunger will be replenished
吞噬 I-III : 殺死一個實體後，有機率恢復飽食度
---
Ice Aspect I-II: Slows the target down on each hit (more slowness per level)
冷凍 I-II : 每次命中時短暫緩速目標
---
Poison Aspect: Poisons the target on each hit
放毒 : 每次命中時短暫使目標中毒
---
Experience I-II: Grants the user more experience when killing entities
經驗獎勵 I-II : 殺死目標時獲得更多的經驗
---
Beheading: Has a 5% chance for Creepers, Zombies, and Skeletons to drop their head when killed
斬首 : 殺死苦力怕、殭屍、骷髏時有5%機率掉落頭顱
---
Paralysis: Upon hitting a target the target will be frozen and have extremely low attack speed. Lasts for 2 seconds.
癱瘓 : 每次命中時使目標無法移動且降低攻速，持續兩秒
---
God of the Sea: Grants water breathing while the user is holding the enchanted item
海神 : 手持帶有此附魔的三叉戟時提供水中呼吸效果
---
Pyromania I-II: Deals additional damage per level to entities that are on fire
縱火 I-II : 對已經燃燒的目標造成更多傷害
---
Rise I-III: Upon being hit, the target floats up in the air for a short duration (longer time per level)
漂浮箭 I-III : 被箭矢射中的目標將漂浮一段時間
---
Sniper I-II: The user does more damage the further they are from their target (more damage for higher level)
神射手 I-II : 離目標越遠，箭矢命中時傷害越大
---
Shotgun I-II: Deals more damage the closer you are to the target
霰彈槍 I-II : 離目標越近，箭矢命中時傷害越大
#ISSUE : In the actual test of long-range hits and personal hits, the damage will only increase by 1
---
Charged Bolt: Has a 30% chance to strike hit targets with lightning
帶電螺栓 : 有30%機率箭矢命中目標時觸發閃電
---
Homing: Projectiles fired from the bow will move towards and hit mobs nearby
追魂箭 : 箭矢會自動追蹤射程附近的敵對生物並命中
#ISSUE : The name of this book in the game is not "Homing", it is Soul Seeker
---
Pulse: Shoots a sonic beam that targets the nearest mob for the cost of slower charge and additional durability loss
聲波 : 改變弩的本質，對最近的目標發射聲波尖嘯
#ISSUE : Even if there are other monsters around, there is a high chance of hurting yourself and neutral creatures
---
Tank I-V: Grants the user 1.5 extra hearts per level
坦克 I-V : 隨此附魔每等級提供額外1.5顆心給使用者
#ISSUE : The actual description I see in the game is different from the web page,
In-game description: Grants the User protection from unblockable and armor bypassing damage
translate : 為使用者提供來自無法阻擋以及繞過護甲的傷害保護
Actually using this enchant still gives increased hearts but always increases the wrong amount and removes the armor description
---
Ender Mind: When the user is hit and is below 4 hearts, they get automatically teleported away (short distance)
終界意識 : 當使用者被攻擊且生命值將低於四顆心時，將短距離隨機傳送
---
Nocturnal: When the user is hit in the night they become invisble for a short duration
夜梟 : 當使用者在夜晚遭受攻擊時，將短暫隱形自身
---
Sugar Rush: Upon killing an entity the wearer becomes fast and has increased jump height
腎上腺素 : 殺死目標時短暫提升跑速與跳躍能力
---
Pumpkin Head: The user can stare at enderman directly without enderman attacking them
南瓜頭 : 獲得直視終界使者的能力而不需要配戴南瓜
---
Glimmering: Stops piglins from attack you straight away like wearing gold armor
閃閃發光 : 獲得豬布林的信賴而不需要穿著金製套裝
---
Double Swing: Has a 5% chance for the user's Axe to swing twice
雙擺 : 有5%的機率一次攻擊直接造成大量傷害
---
God of Thunder: Has a 5% chance for lightning to summon upon the target
雷神索爾 : 有5%的機率召喚閃電攻擊目標
---
Auto Smelting: Allows the player to recieve smelted versions of any block they break. Works with every block that can be smelted.
冶煉 : 使用帶有冶煉附魔的工具挖掘方塊時直接獲得冶煉後的物品
---
Replenish: Instantly consumes seeds and replants a crop when broken
播種 : 使用帶有播種附魔的鋤頭，在收成作物時立刻消耗種子並重新種植作物
---

Looking forward to the update of Traditional Chinese~<3
All content with errors is present in version 0.8.1 (1.19.2)

**Comment by Safrodev** [comment]
Thanks so much! I will also look into the issues you mentioned.

**Comment by oddcrafti** [comment]
I found "Homing", he is called "Soul Seeker" in the game, lol
I have updated this issue to the article
Meanwhile I updated some translations

**Comment by Safrodev** [comment]
Yes, there was a mistake on the main page sorry. Soul seeker is the correct name thank you again!
