### ISSUE TITLE
Tank enchantment overrides armour and armour toughness on chestplate

### ISSUE THREAD

**Issue by spicata** [Safrodev/fabricenchantments#57]
# Details

Fabric 1.19.2, installed server-side and client-side. Fabric Enchantments version 0.8.1 (1.19.2)

# Overview

The tank enchantment seems to override the armour (and armour toughness and knockback resistance for Netherite) when it is put on chestplate.

Unsure if this is simply a visual glitch or actually has an impact on gameplay. If this is actually how it is meant to work, then please put it on the CurseForge page.

# Steps to reproduce

1. Put the tank enchantment on a chestplate.

## Results

1. Notice that the +8[^1] armour stat is missing, instead replaced with +7.5[^2] max health
1. Notice that the armour points on HUD is decreased.

[^1]: For Netherite
[^2]: For Tank V

**Comment by spicata** [comment]
Another thing is that, even after disenchanting at the grindstone, the effects of the Tank enchantment doesn't disappear, and the armour doesn't come back.

**Comment by EddieTheEd** [comment]
I am experiencing the same issue. Hopefully this gets fixed soon :)

**Comment by spicata** [comment]
Is has come to my attention that my server is running the wrong version. Sorry for any inconvenience :*)*

**Comment by Safrodev** [comment]
Oh alright, sorry for the late reply. Please let me know if it still doesn’t work in the latest version.
