### ISSUE TITLE
Pulse enchantment targets the user

### ISSUE THREAD

**Issue by GXyon** [Safrodev/fabricenchantments#58]
When a crossbow with the Pulse enchantment is used and there are no mobs within 8-10 blocks (guesstimated), the projectile will target the user instead, making it unusable for long-range combat. Would it be possible to make the user untargetable by default, and adding an option to exclude other players from being targeted?

Fabric Version: 1.19.2
Mod Version: fabric-enchantments-0.9.0
Fabric Mod List: https://pastebin.com/ui97JtmA

**Comment by Safrodev** [comment]
This is a known bug, I will try to get a fix out soon
