### ISSUE TITLE
Auto-Smelt causes cascading stack errors

### ISSUE THREAD

**Issue by TheIllusiveC4** [Safrodev/fabricenchantments#59]
Minecraft Version: 1.19.3
Fabric API:  0.73.2+1.19.3
Fabric Enchantments: 0.9.1

This piece of code:
https://github.com/Safrodev/fabricenchantments/blob/db31920a375fa5bfe520f3411c602160fd551d87/src/main/java/safro/fabric/enchantments/mixin/AutoSmeltMixin.java#L37-L39

Causes cascading stack errors because it does not copy the output stack it's referencing, it uses it directly. This means that any reference to that stack will be affected by these changes, which is a problem because most smelting recipe outputs are used as a singleton and this code will generate multiple copies of the same stack instance. This leads to issue like stacks not merging correctly when dropped (essentially deleting most of the drops) and recipes failing due to empty outputs.

**Steps to Reproduce:**
1. Enchant a pickaxe with Auto-Smelt
2. Give yourself 6 Stone and place them close together
3. Mine them until 3 or more drop close enough to merge, reset placements if they don't
4. When a large enough merge takes place, pick up the result
5. Observe that the resulting stack should be greater than 2 but is only 2
6. Observe that placing a Cobblestone in a Furnace is no longer a valid recipe

Edit: For full context, someone else brought this bug to my attention and they reported it on 1.19.2 so this affects that version as well.

**Comment by Safrodev** [comment]
I see, thank you for the detailed bug report. I'm surprised I didn't notice this earlier, I'll try to get a fix out soon!
