### ISSUE TITLE
Nocturnal enchantments appear to be quite ineffective.

### ISSUE THREAD

**Issue by MilkissWhite** [Safrodev/fabricenchantments#62]
When I saw the trigger and effect of the Nocturnal enchantment, I assumed that the purpose of the enchant was to delay the time between being attacked and being exposed to additional attacks.

 However, after trying it out myself, I found that the Nocturnal enchantment didn't produce the results I was hoping for.
 In Minecraft, mobs are less likely to recognize players who are invisible, which decreases the more armor you wear. Also, applying invisibility when you're already visible to mobs doesn't necessarily make them stop paying attention to you.
 Since the Nocturnal enchantment is a helmet-only enchantment, the player will inevitably be wearing at least 1 piece of armor when it triggers. Also, since the trigger for the Nocturnal enchantment is being attacked, it's easy to imagine that the player would be wearing more armor in more places if they were trying to prepare for actually taking damage. The benefit of invisibility for a player in this state would be minimal, so the mob that just damaged you would have no problem continuing to recognize you and attack you in rapid succession.
 If we consider a situation where you're facing a player instead of a mob (a PVP situation), the armor you're wearing (in this case, the helmet enchanted by Nocturnal) is still visible, so you don't get the benefit of being invisible.

 Currently, the Nocturnal enchantment is a single-effect enchantment that doesn't vary in effectiveness based on level, has a passive rather than active effect, and has the additional trigger of only being able to be used at night in addition to taking damage. The invisibility effect doesn't do much more than make you temporarily unrecognizable to the mob that just attacked you, so the effect doesn't feel as dramatic as it should for how tricky it is to use.
 If you're looking for an enchantment to get you out of a crisis situation where you're being attacked, there's the Ender Mind enchantment, which is placed on the same helmet area, although it triggers when you're taking more damage, which makes the Nocturnal enchantment feel even more impractical.

 Why not remake the Nocturnal enchantment with a different purpose?
 Personally, I'd suggest reversing the current effect and turning it into an enchantment that grants invisibility continuously at night, but briefly loses invisibility when attacking or being attacked.
 It's a persistent effect that would make sense for a single enchantment with no level scaling, and since it's an enchantment that assumes you won't be in combat in the first place, it would make it less objectionable to wear only a helmet and no armor elsewhere for maximum effectiveness.
 Even if we don't adopt this suggestion, I would still like to see the effect of the Nocturnal enchantment remade.

##Translated with www.DeepL.com/Translator (free version)##

**Comment by Safrodev** [comment]
I have taken your suggestion and it's been changed in the latest version
