### ISSUE TITLE
Auto Smelting can be applied to tools with Silk Touch with an anvil but then it will have no effect

### ISSUE THREAD

**Issue by palapapa** [Safrodev/fabricenchantments#69]
The effect of Silk Touch overrides that of Auto Smelting. It would be better if these two are mutually exclusive so the player doesn't accidentally waste an enchanted book.

**Comment by palapapa** [comment]
I just tested with a pickaxe that has only Auto Smelting on it and it still had no effect at all. I checked the log but didn't find any useful information.
[latest.log](https://github.com/Safrodev/fabricenchantments/files/12096966/latest.log)

**Comment by Safrodev** [comment]
Has been changed, you shouldn't be able to use silk touch with it now
